# Generated by Django 5.2.1 on 2025-06-01 01:34

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=chat.models.default_expiry),
        ),
    ]
